# -*- coding: utf-8 -*-
"""67160158_นายชินภัทร เบลเลอร์_Football Events

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JYbNRRnRHUcHIHUAGqYWWtiQnHNFqMMo
"""

import re
import csv
import gc
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.compose import ColumnTransformer
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, log_loss, mean_squared_error
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC, LinearSVC, NuSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

"""**อ่านไฟล์CSV**

ทำการตรวจสอบข้อมูล (จำนวนข้อมูลทั้งหมด , ตัวแปรทั้งหมด)
"""

data1 = pd.read_csv('/content/events.csv', encoding='latin1', engine='python')
newdf = data1
print('Shape :',newdf.shape)

"""ทำการตรวจสอบข้อมูลก่อนนำข้อมูลไปใช้"""

newdf.head()

print('Info :\n' ,newdf.info())

print(newdf.describe())

"""อ่านไฟล์.txt"""

txt = open("/content/ครูอ้อมครับ.txt","r")

txt.read()

"""ทำการทดสอบลองเช็คข้อมูลในไฟล์"""

data_shot = newdf[newdf.event_type == 1]

messi = (data_shot.player == 'lionel messi')
ronaldo = (data_shot.player == 'cristiano ronaldo')

nb_shot_messi = data_shot.id_odsp[messi].count()
nb_goal_messi = data_shot.id_odsp[messi][data_shot.is_goal == 1].count()
ratio_messi = nb_goal_messi / nb_shot_messi

nb_shot_ronaldo = data_shot.id_odsp[ronaldo].count()
nb_goal_ronaldo = data_shot.id_odsp[ronaldo][data_shot.is_goal == 1].count()
ratio_ronaldo = nb_goal_ronaldo / nb_shot_ronaldo

print('Number of goals for Messi : ', nb_goal_messi)
print('shot ratio for Messi : ', nb_shot_messi)
print(f'Goal/shot ratio for Messi : {ratio_messi:.2f}')
print('Number of goals for Ronaldo : ', nb_goal_ronaldo)
print('shot of goals for Ronaldo : ', nb_shot_ronaldo)
print(f'Goal/shot ratio for Ronaldo : {ratio_ronaldo:.2f}')

"""เคลียร์ค่าช่องว่างในคอลัมน์ is_goalและบันทึกเก็บเป็นไฟล์ cleaned_shot_data.csv"""

print ('Number of shots not located : ', data_shot.is_goal[newdf.location == 19].count())
print ('Split by goal or no goal : ', data_shot.is_goal[newdf.location == 19].value_counts())
print('\
      ')
print('Number of shot recorded', data_shot.is_goal.count())

data_shot_cleaned = data_shot[data_shot.location != 19]
data_shot_cleaned.to_csv('cleaned_shot_data.csv', index=False)
print("บันทึกไฟล์ cleaned_shot_data.csv สำเร็จแล้ว!")

"""ทำการตรวจสอบข้อมูลก่อนนำข้อมูลไปใช้หลังจัดการ is_goal"""

data = pd.read_csv('/content/cleaned_shot_data.csv', encoding='latin1', engine='python')
newdf1 = data
print('Shape :',newdf1.shape)

print('Info :\n' ,newdf1.info())

print(newdf1.describe())

"""กำหนดตัวแปร X ตัวแปร Y"""

X = data_shot[['time', 'side', 'bodypart', 'location', 'situation', 'assist_method', 'fast_break']]
y = data_shot['is_goal']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, stratify=y, random_state=42)

print("สัดส่วนลูกยิงเข้าในชุด Train: {:.2%}".format(y_train.mean()))
print("สัดส่วนลูกยิงเข้าในชุด Test: {:.2%}".format(y_test.mean()))

"""เปรียบเทียบโมเดลเพื่อเป็นตัวเลือกในการตัดสินใจ"""

classifiers = [
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    AdaBoostClassifier(),
    GradientBoostingClassifier(),
    KNeighborsClassifier(),
]

for clf in classifiers:
    clf.fit(X_train, y_train)
    name = clf.__class__.__name__

    print("="*30)
    print(name)

    print('****Results****')
    train_predictions = clf.predict(X_test)

    # 1. หา Accuracy (ความแม่นยำ)
    acc = accuracy_score(y_test, train_predictions)
    print("R-squared (R²): {:.2%}".format(acc))

    # 2. หา MSE (Mean Squared Error)
    mse = mean_squared_error(y_test, train_predictions)
    print("MSE: {:.4f}".format(mse))

    # 3. หา RMSE (Root Mean Squared Error)
    rmse = np.sqrt(mse) # หรือใช้สูตร mse ** 0.5 ก็ได้ครับ
    print("RMSE: {:.4f}".format(rmse))

print("="*30)

"""สรุปโมเดลที่เหลือคือ "GradientBoostingClassifier"
"""

from sklearn.ensemble import GradientBoostingClassifier
model = GradientBoostingClassifier()
model.fit(X_train, y_train)
print(f'XGBoost model precision on test dataset : , {model.score(X_test, y_test) * 100:.2f}')

data_shot.is_goal.value_counts()

data_shot = data_shot[data_shot.location != 19]
X = data_shot[['time', 'side', 'bodypart', 'location', 'situation', 'assist_method', 'fast_break']]
probas = model.predict_proba(X)
data_shot['xgoalpercent'] = probas[:, 1]
print(f'Maximum xG value for a shot : , {probas[:,1].max():.4f}')
print(f'Minimum xG value for a shot : , {probas[:,1].min():.4f}')

messi = (data_shot.player == 'lionel messi')
ronaldo = (data_shot.player == 'cristiano ronaldo')

print('Lionel Messi :')
nb_shot_messi = data_shot[messi]['id_odsp'].count()
print('Number of shots for : ', nb_shot_messi)

xg_messi = data_shot[messi]['xgoalpercent'].sum()

print(f'Expected goals for : {xg_messi:.0f}')

nb_goal_messi = data_shot[(data_shot.is_goal == 1) & messi]['id_odsp'].count()
print('Number of goals for : ', nb_goal_messi)

print(f'Difference between goals and xG : {nb_goal_messi - xg_messi:.0f}')
print(f'xG/shots : {xg_messi / nb_shot_messi:.2f}')

print('\n------------------------\n')

print('Cristiano Ronaldo :')
nb_shot_ronaldo = data_shot[ronaldo]['id_odsp'].count()
print('Number of shots : ', nb_shot_ronaldo)

xg_ronaldo = data_shot[ronaldo]['xgoalpercent'].sum()

print(f'Expected goals : {xg_ronaldo:.0f}')

nb_goal_ronaldo = data_shot[(data_shot.is_goal == 1) & ronaldo]['id_odsp'].count()
print('Number of goals : ', nb_goal_ronaldo)

print(f'Difference between goals and xG : {nb_goal_ronaldo - xg_ronaldo:.0f}')
print(f'xG/shots : {xg_ronaldo / nb_shot_ronaldo:.2f}')

"""เตรียมทำหน้าWeb"""

from sklearn.model_selection import train_test_split

selected_features = ['time', 'side', 'bodypart', 'location', 'situation', 'assist_method', 'fast_break']
X = data_shot[selected_features]
y = data_shot['is_goal']

feature_names = X.columns.tolist()
print("⚽ Features ที่ใช้ทำนายลูกยิง:", feature_names)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f"\n📈 จำนวนข้อมูล train: {len(X_train):,} แถว")
print(f"📉 จำนวนข้อมูล test: {len(X_test):,} แถว")

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier # นำเข้าโมเดล Gradient Boosting

pipeline = Pipeline([
    ("scaler", StandardScaler()),

    # เปลี่ยนมาใช้ Gradient Boosting ตรงนี้ครับ
    ("classifier", GradientBoostingClassifier(
        n_estimators=100,    # จำนวนต้นไม้ที่จะสร้าง
        learning_rate=0.1,   # ความเร็วในการเรียนรู้ (ถ้าค่าน้อย โมเดลจะค่อยๆ ปรับตัวได้ละเอียดขึ้น)
        max_depth=4,         # ความลึกของต้นไม้ (มักจะตั้งให้น้อยกว่า Random Forest เพื่อไม่ให้มันจำข้อสอบ)
        random_state=42      # ล็อคผลลัพธ์ให้ตรงกันทุกครั้ง
    ))
])

print("⏳ กำลัง Train โมเดล Gradient Boosting ด้วย Pipeline...")
print("(อาจจะใช้เวลานานกว่า Random Forest นิดหน่อยนะครับ เพราะมันสร้างต้นไม้ทีละต้น)")
pipeline.fit(X_train, y_train)
print("✅ Train เสร็จสมบูรณ์แล้ว!")

from sklearn.metrics import accuracy_score, classification_report
import pandas as pd

y_pred = pipeline.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"⚽ Accuracy บน Test Set: {accuracy:.4f} ({accuracy*100:.2f}%)")

print("\n📊 รายงานผลการทำนายแบบละเอียด (Gradient Boosting):")
print(classification_report(y_test, y_pred,
                            target_names=["ยิงไม่เข้า (No Goal)", "ยิงเข้า (Goal)"]))

# ดึงตัวโมเดล Gradient Boosting ออกมาจาก Pipeline
gb_model = pipeline.named_steps["classifier"]

# ดูความสำคัญของแต่ละ Feature
importances = pd.DataFrame({
    "feature": feature_names,
    "importance": gb_model.feature_importances_
}).sort_values("importance", ascending=False)

print("\n🌟 ความสำคัญของแต่ละปัจจัย (Feature Importance):")
print(importances.to_string(index=False))

import pandas as pd

def predict_xg_text(time, side, bodypart, location, situation, assist_method, fast_break):
    """
    ฟังก์ชันทำนาย xG พร้อมระบบค้นหา Top 5 นักเตะที่ยิงสไตล์นี้บ่อยที่สุด
    """
    map_side = {'เหย้า': 1, 'home': 1, 'เยือน': 2, 'away': 2}
    map_bodypart = {'เท้าขวา': 1, 'เท้าซ้าย': 2, 'โหม่ง': 3}

    # 🌟 อัปเดต: เพิ่มตำแหน่งให้ครบทั้ง 19 แบบตาม Data Dictionary
    map_location = {
        'แดนบุก': 1,
        'แดนรับ': 2,
        'กลางกรอบเขตโทษ': 3,
        'ปีกซ้าย': 4,
        'ปีกขวา': 5,
        'มุมแคบและไกล': 6,
        'มุมแคบฝั่งซ้าย': 7,
        'มุมแคบฝั่งขวา': 8,
        'ฝั่งซ้ายของกรอบเขตโทษ': 9,
        'ซ้ายกรอบ 6 หลา': 10,
        'ฝั่งขวาของกรอบเขตโทษ': 11,
        'ขวากรอบ 6 หลา': 12,
        'ยิงจ่อๆ': 13, 'หน้าปากประตู': 13,
        'จุดโทษ': 14,
        'นอกกรอบเขตโทษ': 15,
        'ยิงไกล': 16,
        'ยิงไกลกว่า 35 หลา': 17,
        'ยิงไกลกว่า 40 หลา': 18,
    }

    map_situation = {'โอเพ่นเพลย์': 1, 'เซ็ตพีซ': 2, 'เตะมุม': 3, 'ฟรีคิก': 4}
    map_assist = {'ไม่มี': 0, 'เลี้ยงมาเอง': 0, 'จ่ายปกติ': 1, 'โยน': 2, 'ครอส': 2, 'โหม่งชง': 3, 'จ่ายทะลุช่อง': 4}
    map_fast_break = {'ไม่ใช่': 0, 'ไม่': 0, 'ใช่': 1, 'สวนกลับ': 1}

    def clean_text(text):
        return str(text).strip()

    try:
        side_code = map_side[clean_text(side)]
        body_code = map_bodypart[clean_text(bodypart)]
        loc_code = map_location[clean_text(location)]
        sit_code = map_situation[clean_text(situation)]
        ast_code = map_assist[clean_text(assist_method)]
        fb_code = map_fast_break[clean_text(fast_break)]
    except KeyError as e:
        print(f"\n❌ ระบบไม่รู้จักคำว่า {e} ครับ (โปรดตรวจสอบการสะกดคำให้ตรงกับตัวเลือก)")
        return

    # 1. เตรียมข้อมูลเพื่อส่งให้โมเดลทำนาย
    input_data = pd.DataFrame({
        'time': [time],
        'side': [side_code],
        'bodypart': [body_code],
        'location': [loc_code],
        'situation': [sit_code],
        'assist_method': [ast_code],
        'fast_break': [fb_code]
    })

    # 2. คำนวณ xG (เปลี่ยนเป็น pipeline ตามที่เราเทรนไว้ล่าสุดครับ)
    xg_prob = pipeline.predict_proba(input_data)[0, 1]

    # 3. ค้นหา Top 5 นักเตะจากตาราง data_shot
    similar_shots = data_shot[
        (data_shot['bodypart'] == body_code) &
        (data_shot['location'] == loc_code) &
        (data_shot['situation'] == sit_code) &
        (data_shot['assist_method'] == ast_code) &
        (data_shot['fast_break'] == fb_code)
    ]

    print("\n" + "="*45)
    print("⚽ ผลการวิเคราะห์ Expected Goals (xG) ⚽")
    print("="*45)
    print(f"⏱️ นาทีที่: {time} | 🏟️ เล่นเป็นทีม: {side}")
    print(f"📍 ตำแหน่ง: {location} | 🦵 ใช้: {bodypart}")
    print(f"📋 รูปแบบการเล่น: {situation} | 👟 การส่งบอล: {assist_method} | ⚡ สวนกลับ: {fast_break}")
    print("-" * 45)
    print(f"🎯 โอกาสที่จะเป็นประตู: {xg_prob * 100:.2f}% (ค่า xG = {xg_prob:.4f})")

    # 4. แสดงผล Top 5 นักเตะ
    print("\n🌟 Top 5 นักเตะที่ได้ง้างเท้ายิงสไตล์นี้บ่อยที่สุด 🌟")
    if len(similar_shots) > 0:
        top_players = similar_shots['player'].value_counts().head(5)
        for i, (player, count) in enumerate(top_players.items(), 1):
            print(f"  {i}. {player.title()} : {count} ครั้ง")
    else:
        print("  - ไม่พบสถิตินักเตะที่ยิงด้วยเงื่อนไขเป๊ะๆ แบบนี้ในฐานข้อมูลครับ -")
    print("="*45)

# ==========================================
# ส่วนของการโต้ตอบกับผู้ใช้งาน (Interactive)
# ==========================================
print("=== ระบบกรอกข้อมูลจำลองลูกยิง ===")
print("(กรุณาพิมพ์คำตอบให้ตรงกับตัวเลือกในวงเล็บนะครับ)\n")

try:
    user_time = int(input("1. นาทีที่ยิง (ใส่ตัวเลข เช่น 45, 90) : "))
    user_side = input("2. เป็นทีมเหย้า หรือ ทีมเยือน? (เหย้า / เยือน) : ")
    user_bodypart = input("3. ใช้ส่วนไหนยิง? (เท้าขวา / เท้าซ้าย / โหม่ง) : ")

    # จัดเรียงตัวเลือกให้เป็นระเบียบ อ่านง่ายขึ้น
    print("\n📍 ตัวเลือกตำแหน่ง:")
    print("   [หน้าปากประตู / จุดโทษ / กลางกรอบเขตโทษ / ซ้ายกรอบ 6 หลา / ขวากรอบ 6 หลา]")
    print("   [ฝั่งซ้ายของกรอบเขตโทษ / ฝั่งขวาของกรอบเขตโทษ / มุมแคบฝั่งซ้าย / มุมแคบฝั่งขวา]")
    print("   [นอกกรอบเขตโทษ / ยิงไกล / ยิงไกลกว่า 35 หลา / ยิงไกลกว่า 40 หลา / มุมแคบและไกล]")
    print("   [ปีกซ้าย / ปีกขวา / แดนบุก / แดนรับ / ไม่ได้บันทึก]")
    user_location = input("4. ตำแหน่งที่ยิง? : ")

    user_situation = input("5. รูปแบบการเล่น? (โอเพ่นเพลย์ / เตะมุม / ฟรีคิก / เซ็ตพีซ) : ")
    user_assist = input("6. การได้บอลมาก่อนยิง? (ไม่มี / จ่ายปกติ / โยน / โหม่งชง / จ่ายทะลุช่อง) : ")
    user_fast_break = input("7. เป็นจังหวะสวนกลับเร็วหรือไม่? (ใช่ / ไม่ใช่) : ")

    print("\nกำลังวิเคราะห์ข้อมูล... ⏳")
    predict_xg_text(user_time, user_side, user_bodypart, user_location, user_situation, user_assist, user_fast_break)

except ValueError:
    print("\n❌ กรุณากรอก 'นาทีที่ยิง' เป็นตัวเลขเท่านั้นครับ!")

import joblib
import json
from datetime import datetime

# ==========================================
# โค้ดสำหรับ Save โมเดลออกเป็น 3 ไฟล์
# ==========================================

# 1. บันทึกไฟล์ Pipeline (.pkl)
# ตัวแปร pipeline คือตัวที่เราเทรน Gradient Boosting ไว้แล้ว
pipeline_filename = 'xg_pipeline.pkl'
joblib.dump(pipeline, pipeline_filename)
print(f"✅ 1. สร้างไฟล์โมเดล: {pipeline_filename}")

# 2. บันทึกไฟล์ Feature Names (เป็น JSON)
# ตัวแปร feature_names เราเคยประกาศไว้แล้วก่อนหน้านี้
feature_filename = 'feature_names.json'
with open(feature_filename, 'w', encoding='utf-8') as f:
    json.dump(feature_names, f, ensure_ascii=False, indent=4)
print(f"✅ 2. สร้างไฟล์รายชื่อตัวแปร: {feature_filename}")

# 3. บันทึกไฟล์ Model Metadata (เป็น JSON)
# สร้างดิกชันนารีเก็บข้อมูลรายละเอียดของโมเดลที่เราอยากจำไว้
metadata = {
    "project_name": "Football Expected Goals (xG) Prediction",
    "model_type": "GradientBoostingClassifier",
    "target_classes": {"0": "ยิงไม่เข้า", "1": "ยิงเข้า"},
    "accuracy_score": round(float(accuracy), 4), # ดึงค่า accuracy จากเซลล์ก่อนหน้ามาใส่
    "created_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
}

metadata_filename = 'model_metadata.json'
with open(metadata_filename, 'w', encoding='utf-8') as f:
    json.dump(metadata, f, ensure_ascii=False, indent=4)
print(f"✅ 3. สร้างไฟล์รายละเอียดโมเดล: {metadata_filename}")

print("\n🎉 สร้างไฟล์สำหรับทำเว็บ Streamlit เสร็จสมบูรณ์ทั้ง 3 ไฟล์แล้วครับ!")
print("👉 อย่าลืมกดคลิกขวาที่ไฟล์ทั้ง 3 ตัวที่แถบด้านซ้ายมือของ Colab แล้วเลือก 'Download' ลงเครื่องนะครับ")

"""***สร้างตารางความสัมพันธ์ ( Correlation Heatmap )***"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# 1. พจนานุกรมแปลรหัส location เป็นชื่อตำแหน่ง (อัปเดตครบทั้ง 19 ตำแหน่งตามภาพ)
location_dict = {
    1: '1.Attacking half', #(แดนบุก)
    2: '2.Defensive half', #(แดนรับ)
    3: '3.Centre of the box', #(กลางกรอบเขตโทษ)
    4: '4.Left wing', #(ปีกซ้าย)
    5: '5.Right wing', #(ปีกขวา)
    6: '6.Difficult angle and long range', #(มุมแคบและไกล)
    7: '7.Difficult angle on the left', #(มุมแคบฝั่งซ้าย)
    8: '8.Difficult angle on the right', #(มุมแคบฝั่งขวา)
    9: '9.Left side of the box', #(ฝั่งซ้ายของกรอบเขตโทษ)
    10: '10.Left side of the six yard box', #(ซ้ายกรอบ 6 หลา)
    11: '11.Right side of the box', #(ฝั่งขวาของกรอบเขตโทษ)
    12: '12.Right side of the six yard box', #(ขวากรอบ 6 หลา)
    13: '13.Front of the box', #(หน้าปากประตู)
    14: '14.Penalty spot', #(จุดโทษ)
    15: '15.Outside the box', #(นอกกรอบเขตโทษ)
    16: '16.Long range', #(ยิงไกล)
    17: '17.More than 35 yards', #(ยิงไกลกว่า 35 หลา)
    18: '18.More than 40 yards ', #(ยิงไกลกว่า 40 หลา)
}

# 2. จับกลุ่มข้อมูลตาม location และคำนวณสถิติ
location_stats = data_shot.groupby('location')['is_goal'].agg(
    Total_Shots='count',      # จำนวนครั้งที่ยิงทั้งหมด
    Goals='sum',              # จำนวนประตูที่ทำได้
    Goal_Percentage='mean'    # อัตราการยิงเข้า (ค่า mean ของ 0 กับ 1 คือ % การเข้าครับ)
).reset_index()

# 3. แปลงตัวเลขเป็นเปอร์เซ็นต์ และใส่ชื่อตำแหน่งให้ดดูง่าย
location_stats['Goal_Percentage'] = location_stats['Goal_Percentage'] * 100
location_stats['Location_Name'] = location_stats['location'].map(location_dict)

# 4. กรองเอาเฉพาะตำแหน่งที่มีการยิงอย่างน้อย 100 ครั้ง (ตัดพวกข้อมูลแปลกๆ ออก)
location_stats = location_stats[location_stats['Total_Shots'] >= 100]

# 5. เรียงลำดับจาก โอกาสเข้ามากที่สุด -> ไปน้อยที่สุด
location_stats = location_stats.sort_values('Goal_Percentage', ascending=False)

# ปริ้นท์ตารางสถิติออกมาดู
print("🎯 จัดอันดับตำแหน่งที่มีโอกาสยิงเข้าสูงสุด (Goal Conversion Rate)\n")
print(location_stats[['Location_Name', 'Total_Shots', 'Goals', 'Goal_Percentage']].to_string(index=False))

# 6. วาดกราฟแท่ง (Bar Chart)
# ปรับความสูงกราฟเป็น 10 เพื่อให้แสดงข้อมูลได้ครบทุกตำแหน่งโดยไม่เบียดกันเกินไป
plt.figure(figsize=(12, 10))
sns.barplot(data=location_stats, x='Goal_Percentage', y='Location_Name', palette='RdYlGn_r')

plt.title('Goal Conversion Rate by Location (%)', fontsize=16)
plt.xlabel('Success Rate (%)', fontsize=12)
plt.ylabel('Shot Location', fontsize=12)
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.show()

correlation_matrix1 = newdf1.select_dtypes(include=['number']).corr()

numeric_data = data_shot.select_dtypes(include=['number', 'float', 'int'])
correlation_matrix1 = numeric_data.corr()
plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix1, annot=True, cmap='coolwarm', center=0, fmt='.2f')
plt.title('Correlation Heatmap')
plt.show()

selected_cols = ['time', 'side', 'bodypart', 'location', 'situation', 'assist_method', 'fast_break', 'is_goal']

corr_matrix_selected = data_shot[selected_cols].corr()

plt.figure(figsize=(10, 8))

sns.heatmap(corr_matrix_selected, annot=True, cmap='coolwarm', center=0, fmt='.2f', linewidths=0.5)

plt.title('Correlation Heatmap: Features vs is_goal', fontsize=14)
plt.show()

"""***สร้าง Box Plot***"""

def read_data_from_csv(file_path):
    """
    Reads data, checks columns, converts to numeric, handles missing values.
    Selects only numeric columns.
    """
    try:
        df = pd.read_csv(file_path)

        required_numeric_cols = ['time', 'side', 'bodypart', 'location', 'situation', 'assist_method', 'fast_break', 'is_goal']

        missing_cols = [col for col in required_numeric_cols if col not in df.columns]
        if missing_cols:
            raise ValueError(f"Missing required columns: {', '.join(missing_cols)}")

        df_numeric = df[required_numeric_cols].copy() # เพิ่ม .copy() เพื่อป้องกันคำเตือน SettingWithCopyWarning

        for col in required_numeric_cols:
            df_numeric[col] = pd.to_numeric(df_numeric[col], errors='coerce')

        df_numeric = df_numeric.dropna()
        df_numeric = df_numeric.reset_index(drop=True)

        return df_numeric

    except FileNotFoundError:
        print(f"Error: File not found at '{file_path}'")
        return None
    except pd.errors.EmptyDataError:
        print(f"Error: CSV file '{file_path}' is empty.")
        return None
    except ValueError as ve:
        print(f"Error: {ve}")
        return None
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return None

def create_boxplots(df):
    """
    Creates and displays box plots for each numeric column in the DataFrame.
    """
    for column in df.columns:
        plt.figure(figsize=(16, 4))
        sns.boxplot(x=df[column])
        plt.title(f'Box Plot of {column}')
        plt.xlabel(column)

        # แสดงกราฟบนหน้าจอ
        plt.show()
        plt.close()

if __name__ == "__main__":
    file_path = "/content/cleaned_shot_data.csv"
    df_numeric = read_data_from_csv(file_path)

    if df_numeric is not None:
        create_boxplots(df_numeric)

"""***สร้างกราฟ Scatter Plot***"""

def read_data_from_csv(file_path):
    """
    Reads data from a CSV file, checks for required columns,
    converts them to numeric, and handles missing values.

    Args:
        file_path (str): Path to the CSV file.

    Returns:
        pandas.DataFrame: DataFrame with data from CSV, or None if an error occurs.
    """
    try:
        df = pd.read_csv(file_path)
        required_cols = ['time', 'side', 'bodypart', 'location', 'situation', 'assist_method', 'fast_break','is_goal']



        for col in required_cols:
            if col not in df.columns:
                raise ValueError(f"Column '{col}' not found in the CSV file.")
            df[col] = pd.to_numeric(df[col], errors='coerce')

        df.dropna(subset=required_cols, inplace=True)
        df.reset_index(drop=True, inplace=True)

        return df

    except FileNotFoundError:
        print(f"Error: File not found at '{file_path}'")
        return None
    except pd.errors.EmptyDataError:
        print(f"Error: CSV file '{file_path}' is empty.")
        return None
    except ValueError as ve:
        print(f"Error: {ve}")
        return None
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return None


def plot_with_equation(x_col, y_col, df, color):
    """
    Creates a scatter plot, regression line, and displays the equation.

    Args:
      x_col: The name of the column for the x-axis.
      y_col: The name of the column for the y-axis.
      df: The pandas DataFrame.
      color: The color of the regression line.
    """

    df = df.dropna(subset=[x_col, y_col])

    if df.empty:
        print(f"Skipping plot for {x_col} vs. {y_col} due to missing data.")
        return

    plt.figure(figsize=(8, 6))
    sns.regplot(x=x_col, y=y_col, data=df, scatter_kws={'alpha': 0.5}, line_kws={'color': color})

    model = LinearRegression()
    model.fit(df[[x_col]], df[y_col])

    equation = f'{y_col} = {model.coef_[0]:.2f} * {x_col} + {model.intercept_:.2f}'

    plt.text(0.1, 0.9, equation, transform=plt.gca().transAxes, fontsize=12, color=color)

    plt.title(f'{x_col} vs. {y_col}')
    plt.xlabel(x_col)
    plt.ylabel(y_col)
    plt.grid(True, alpha=0.3)
    plt.show()

if __name__ == "__main__":
    file_path = '/content/cleaned_shot_data.csv'
    df = read_data_from_csv(file_path)

    if df is not None:

        plot_with_equation('time', 'is_goal', df, 'Red')
        plot_with_equation('side', 'is_goal', df, 'Red')
        plot_with_equation('bodypart', 'is_goal', df, 'Red')
        plot_with_equation('location', 'is_goal', df, 'Red')
        plot_with_equation('situation', 'is_goal', df, 'Red')
        plot_with_equation('assist_method', 'is_goal', df, 'Red')
        plot_with_equation('fast_break', 'is_goal', df, 'Red')